name = "reverse_littlewood_offord_lean4web"
version = "0.1.0"
defaultTargets = ["ReverseLittlewoodOffordLean4Web"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[lean_lib]]
name = "ReverseLittlewoodOffordLean4Web"
