#!/usr/bin/env python3
"""Bundle the modular development in ../lean into one mathlib-only file for Lean4Web.

Usage (from the repository root):  python3 tools/export_lean4web.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LEAN = ROOT / "lean"
OUT = ROOT / "lean4web" / "ReverseLittlewoodOffordLean4Web.lean"

MODULES = [
    "ReverseLittlewoodOfford/Defs.lean",
    "ReverseLittlewoodOfford/AlternatingSum.lean",
    "ReverseLittlewoodOfford/Normalization.lean",
    "ReverseLittlewoodOfford/HereditaryDeletion.lean",
    "ReverseLittlewoodOfford/Concentration.lean",
    "ReverseLittlewoodOfford/LowerBound.lean",
    "ReverseLittlewoodOfford/UpperConstruction.lean",
    "ReverseLittlewoodOfford/Limit.lean",
    "ReverseLittlewoodOfford/Rate.lean",
    "ReverseLittlewoodOffordFC.lean",
]
AUDIT = "ReverseLittlewoodOffordVerified.lean"

HEADER = '''import Mathlib

/-!
# Reverse Littlewood–Offord problem at radius one — standalone file

Generated by tools/export_lean4web.py from the modular development in ../lean/.
No project-local imports are required.

Target: ReverseLittlewoodOfford.reverse_littlewood_offord_rate (near the end of this file).
Status: complete. Every component depends only on propext, Classical.choice and Quot.sound.
-/

/-- Formal Conjectures' `answer(t)` elaborates to `t`. -/
syntax:max "answer(" term ")" : term
macro_rules
  | `(answer($p)) => `($p)

set_option autoImplicit false
'''


def body(path: Path) -> str:
    keep = [ln for ln in path.read_text(encoding="utf-8").splitlines()
            if not ln.startswith("import ") and ln.strip() != "set_option autoImplicit false"]
    return "\n".join(keep).strip() + "\n"


def main() -> None:
    parts = [HEADER]
    total = len(MODULES)
    for i, name in enumerate(MODULES, 1):
        parts.append(f"\n/-! ## Component {i}/{total}: {name} -/\n\n" + body(LEAN / name))
    audit = [ln for ln in (LEAN / AUDIT).read_text(encoding="utf-8").splitlines()
             if ln.startswith("#print axioms")]
    parts.append("\n/-! ## Component axiom audit -/\n\n" + "\n".join(audit) + "\n")
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
